---
theme: "polymer"

baseurl: "https://fde-mtl.ca"

paginate: 10

MetaDataFormat: "yaml"
DefaultContentLang: fr

ignoreFiles:
  - "~$"
  - "\\.#"

menu:
  - main
  - footer

Multilingual:
  fr:
    weight: 1

    title: "Famille, développement et éducation"
    languageCode: "fr-CA"

    copyright: "(ɔ) 2015 FDE Montréal. Tous droits renversés."

  en:
    weight: 2

    title: "Family, Development and Education"
    languageCode: "en-CA"

    copyright: "(ɔ) 2015 Copyleft. FDE Montreal."


params:
  # Number of articles in the "Latest news" section on the front page.
  homepage_news: 3
  author: "FDE"
  profile: "images/logo-small-alpha-fr.png"
  facebook: ""
  # TODO: faire le setup
  #googleAnalyticsUserID: "UA-72488186-1"

permalinks:
  posts: "/:year/:month/:day/:slug/"
